object Dependencies {
    const val LIFECYCLE_LIVEDATA_KTX =  "androidx.lifecycle:lifecycle-livedata-ktx:${Version.ANDROIDX_LIFECYCLE}"
    const val LIFECYCLE_VIEWMODEL_KTX =  "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_CORE_KTX = "androidx.core:core-ktx:${Version.ANDROIDX_CORE_KTX}"
    const val ANDROIDX_APPCOMPAT = "androidx.appcompat:appcompat:${Version.ANDROIDX_APPCOMPAT}"
    const val MATERIAL = "com.google.android.material:material:${Version.MATERIAL}"
    const val ANDROIDX_CONSTRAINTLAYOUT = "androidx.constraintlayout:constraintlayout:${Version.ANDROIDX_CONSTRAINTLAYOUT}"
    const val ANDROIDX_LIFECYCLE_LIVEDATA = "androidx.lifecycle:lifecycle-livedata-ktx:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${Version.ANDROIDX_NAVIGATION}"
    const val ANDROIDX_NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${Version.ANDROIDX_NAVIGATION}"
    const val JUNIT_JUNIT ="junit:junit:${Version.JUNIT_JUNIT}"
    const val ANDROIDX_TEST_JUNIT = "androidx.test.ext:junit:${Version.ANDROIDX_TEST_JUNIT}"
    const val ANDROIDX_TEST_ESPRESSO_CORE = "androidx.test.espresso:espresso-core:${Version.ANDROIDX_TEST_ESPRESSO_CORE}"
    const val LOTTIE = "com.airbnb.android:lottie:${Version.LOTTIE}"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:${Version.HILT}"
    const val HILT_COMPILER  ="com.google.dagger:hilt-compiler:${Version.HILT}"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${Version.SWIPE_REFRESH_LAYOUT}"
}